### ISSUE TITLE
Can't load rewards

### ISSUE THREAD

**Issue by TheDJTC** [gottagofaster236/RewardsTheater#11]
Randomly got this error, re-logging in, updating, re-logging in again, doing the past authenticator token thing, removing rewardstheater access to twitch and logging in again, but I keep getting this message.

![image](https://github.com/user-attachments/assets/e9e97e29-995d-4e68-94a3-161741dd6a92)

Haven't seen this error in any searches so if there's a fix to this, I'd be grateful to learn.

Edit: Forgot to add, I did a short stream to make sure OBS isn't blocked from internet, the stream works, as does the pokemon community game browser sources

**Comment by gottagofaster236** [comment]
This is fixed in 1.0.8, please update

**Comment by gottagofaster236** [comment]
https://github.com/gottagofaster236/RewardsTheater/releases/tag/1.0.8

**Comment by TheDJTC** [comment]
ROFL that was fast! Thanx!
