### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by ToRRent1812** [gottagofaster236/RewardsTheater#14]
I use .deb package for rewardstheater, the plugin opens normally, I set up everything and closed obs. Launching obs again shows that none of the settings saved...

Do i need to do something special?

**Comment by gottagofaster236** [comment]
Try exiting OBS via the "Exit" button (see screenshot), does it help?

![IMG_20241021_040000_206.jpg](https://github.com/user-attachments/assets/86a5b196-6f38-4b65-b874-89dbf7c75e40)

**Comment by gottagofaster236** [comment]
Hi again, any updates? Also, I've fixed one possible reason why this could be happening in the latest release :)

**Comment by ToRRent1812** [comment]
I will close it since clicking exit saved everything. Thanks.
