### ISSUE TITLE
OBS Crashing when using RewardsTheater random VLC Source 

### ISSUE THREAD

**Issue by PsycheCyclops** [gottagofaster236/RewardsTheater#15]
Hello! Forgive me if this is not the greatest explanation, I'll try my best to explain what's going on with my OBS!

I am using OBS 30.0.0, along with the latest version of RewardsTheater.
I have a redeem that shows a random video (VLC Video Source), from a folder of currently 276 videos. 

the redeem usually works well, however there seems to be a random chance of crashing my OBS entirely to the point of me needing to force close it via task manager. i'm not sure why: all videos are mp4s, they are under 30 seconds long, and the largest video is 10.6 MB

whenever this happens, it's when a viewer uses the deer video redeem as normal, and causes my OBS to be completely unusable. i can still see my audio meters moving as well as the uptime, CPU usage % and FPS counter continuing to work as normal. however, stream will crash and i have to forcibly close OBS to restart stream.

i'm not sure what else to include information-wise, as this never produces an actual crash report in OBS. if there's anything else i could provide to help, please let me know! thanks in advance!

![2](https://github.com/user-attachments/assets/4c0d049b-fa60-4e3c-aa18-427b28aba5a4)
![1](https://github.com/user-attachments/assets/55d72b8c-2b33-44d4-a423-5635242c2c6c)
![3](https://github.com/user-attachments/assets/7fdb118c-44ac-4f87-ab60-2e33d932e302)

**Comment by gottagofaster236** [comment]
Thanks for the report! I'll try to see if I can reproduce it, but if you could find a way to increase the odds of the crash I'd be very grateful :)

**Comment by gottagofaster236** [comment]
Hi again, sorry, finally got time to look at this.

Could you first try to update OBS **and** VLC to the current versions? Maybe they fixed the bug in their releases already.

If that doesn't help, even though there's no crash report, maybe you at least share the log file? After you kill and restart OBS, you could go to Help → Crash reports → Upload Previous Log File. Thanks!
![image](https://github.com/user-attachments/assets/d4a662d8-920a-440f-91b4-f98eea909469)

**Comment by PsycheCyclops** [comment]
hi again!

after updating to the version in your screenshot (30.1.2) and updating VLC to the latest version, i now have this error whenever I try to use my redeem, despite it being set up the exact same way as before D: even when i set up the VLC source from scratch, it still occurs :(

![image](https://github.com/user-attachments/assets/d7f3f388-1a08-46c8-a095-d98b0cd0b9ef)

**Comment by gottagofaster236** [comment]
Hi, thx for your response, sorry updating broke it for you.
Just to make sure, does everything work if you create a VLC source with only several videos (e.g., 3)?

**Comment by PsycheCyclops** [comment]
I just reverted back to 30.0.0 since i did a stream today, here's the log file after stream (the redeem crashed again but since i didn't touch it, i didn't crash xD) https://obsproject.com/logs/SAZCe1pKI3xxA8Hw

i'll re-update to 30.1.2 and try the VLC source like you said and report back!

**Comment by gottagofaster236** [comment]
> I just reverted back to 30.0.0 since i did a stream today, here's the log file after stream (the redeem crashed/stopped again but since i didn't touch it, i didn't crash OBS entirely xD) https://obsproject.com/logs/SAZCe1pKI3xxA8Hw
> 
> i'll re-update to 30.1.2 and try the VLC source like you said and report back! edit: yep! seems to work with just 3 videos in there. no error!

Ok, so there's nothing useful in the logs unfortunately, but if it works with 3 videos and doesn't with 300, I think I know how I could try to fix this :)

**Comment by gottagofaster236** [comment]
Could you please try again with latest release? It should improve random playback of VLC Sources Playlists by a lot :) https://github.com/gottagofaster236/RewardsTheater/releases/tag/1.1.0

**Comment by PsycheCyclops** [comment]
I absolutely will!!! thank you again so much for making this and taking a look at this issue!!!
i'll be sure to post a new comment if i have any more issues with it crashing. i'll be testing it for the first time this Saturday!

**Comment by PsycheCyclops** [comment]
i did almost an 8 hour stream with no issues! thank you again so much for taking a look at this and solving it so quickly!!! <3

**Comment by gottagofaster236** [comment]
Thanks for confirming! Please lmk if the issue reappears :)
