### ISSUE TITLE
Loop support and close it after a given time

### ISSUE THREAD

**Issue by Eldoran** [gottagofaster236/RewardsTheater#5]
Hi there, I have a media video with alpha channel and I would like to play it in a loop during X seconds or minutes, so for that I would need some feature that allow me to set a time and then hide/close the media file after that time. 
Thanks in advance!

**Comment by gottagofaster236** [comment]
Hi, this feature is added in the latest release, try checking the "Loop video and stop after N seconds" checkbox
<img width="773" alt="image" src="https://github.com/user-attachments/assets/e8e8b255-e1d6-4381-8414-482b240b1892" />
