### ISSUE TITLE
Rewards Theater not appearing in Tools

### ISSUE THREAD

**Issue by nixonfitzpatrick** [gottagofaster236/RewardsTheater#7]
I've tried running the installer, and doing the installation with just the Zip files, but I can't get the plugin to appear in the Tools menu.  OBS is version 29.1.3 and everything is set to default installation directories. Any help would be greatly appreciated.

**Comment by gottagofaster236** [comment]
Hi, OBS 29.1.3 is not supported anymore with the newest version of the plugin (only OBS 30+). Try installing version 1.0.5 instead

**Comment by nixonfitzpatrick** [comment]
That worked! Thank you so much for making this and for helping me.  Your work, generosity, and kindness are greatly appreciated

**Comment by gottagofaster236** [comment]
No problem! If you could share, which one of the two things helped: updating OBS or updating Visual Studio Redistributable? (Just so that I could write that for other users as well)
