### ISSUE TITLE
RewardsTheater won't authenticate through browser. Need access token but don't know how!

### ISSUE THREAD

**Issue by Avytaan** [gottagofaster236/RewardsTheater#8]
Been using this plug in for a while and I need to authenticate every so often apparently, but it's not letting me in browser. The page doesn't load, just says THIS PAGE ISN'T WORKING then underneath says "localhost didn't send any data". I have no idea how to authenticate with access token. D: Help?
![thingy](https://github.com/gottagofaster236/RewardsTheater/assets/173213952/9811d201-e0c4-430f-a645-a53c22f9652e)

**Comment by gottagofaster236** [comment]
The first thing to try is to just close OBS and open it again, it can help. If it doesn't, then you can indeed obtain the token manually.

1. Follow this link:
   https://id.twitch.tv/oauth2/authorize?client_id=2u4jgrdekf0pwdpq7cmqcarifv93z3&force_verify=true&redirect_uri=http://localhost:19918/authRedirect&response_type=token&scope=channel:manage:redemptions%20channel:read:redemptions
2. Click "Authorize".
3. Copy the access token from the URL that you get redirected to 
![image](https://github.com/gottagofaster236/RewardsTheater/assets/55288842/d4530208-7974-4be0-aa55-8a944a42fc45)
4. Copy it to this "or authenticate with access token" field.

**Comment by Avytaan** [comment]
I will try this when I'm back on my PC. Thank you so much! 🤩
