### ISSUE TITLE
Latest version crashes OBS

### ISSUE THREAD

**Issue by hgdagon** [gottagofaster236/RewardsTheater#9]
After the latest update OBS would not run in Normal. I haven't even started using the plugin for anything, it was just being loaded on launch. Event viewer shows `MSVCP140.dll` as the faulty module for `obs64.exe`. The log files stop abruptly at `[RewardsTheater] Loading plugin, version 1.0.7`. After uninstalling the plugin, OBS runs again.

**Comment by gottagofaster236** [comment]
I could probably somehow include VS redistributable in the installer, because this is confusing for people 😅

**Comment by hgdagon** [comment]
> > If the plugin doesn't appear or crashes OBS, repair [Visual Studio Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe)

This was actually the reason. I only realized this when multiple unrelated applications were crashing with event viewer mentioning the very same dll.
